import { Metadata } from "next";
import cn from "classnames";
import "sanitize.css";
import { PropsWithChildren } from "react";
import Head from "next/head";

import "~/styles/global.css";
import { sourceSans3, firaMono } from "~/styles/fonts";
import { theme } from "~/styles/theme.css";
import { MenuLink, Navbar } from "~/components/Navbar";
import { Footer } from "~/components/Footer";

import { SocialMediaLinks } from "./SocialMediaLinks";
import { ContentWrapper } from "./ContentWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type HomeLayoutProps = PropsWithChildren;

export default function HomeLayout({ children }: HomeLayoutProps) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={cn(theme, sourceSans3.variable, firaMono.variable)}>
        <Navbar
          menuLinks={MENU_LINKS}
          socialMediaLinks={<SocialMediaLinks />}
        />
        <ContentWrapper>{children}</ContentWrapper>
        <Footer socialMediaLinks={<SocialMediaLinks />} />
      </body>
    </html>
  );
}

const MENU_LINKS: MenuLink[] = [
  {
    href: "/",
    label: "Home",
  },
  {
    href: "/blog",
    label: "Blog",
  },
];
