import { Metadata } from "next";
import cn from "classnames";
import "sanitize.css";
import { PropsWithChildren } from "react";

import "~/styles/global.css";
import { dmSans } from "~/styles/fonts";
import { theme } from "~/styles/theme.css";
import { Navigation } from "~/components/Navigation";
import { Layout } from "~/components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type HomeLayoutProps = PropsWithChildren;

export default function HomeLayout({ children }: HomeLayoutProps) {
  return (
    <html lang="en">
      <body className={cn(theme, dmSans.variable)}>
        <Layout navigation={<LayoutNavigation />}>{children}</Layout>
      </body>
    </html>
  );
}

function LayoutNavigation() {
  return (
    <Navigation>
      <Navigation.Item href={"/about"} isCurrent={true}>
        About
      </Navigation.Item>
      <Navigation.Item href={"/blog"}>Blog</Navigation.Item>
    </Navigation>
  );
}
