import { Metadata } from "next";
import cn from "classnames";
import "sanitize.css";
import { PropsWithChildren } from "react";
import Head from "next/head";

import "~/styles/global.css";
import { dmSans } from "~/styles/fonts";
import { theme } from "~/styles/theme.css";
import { Layout } from "~/components/Layout";

import { AppNavbar } from "./AppNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type HomeLayoutProps = PropsWithChildren;

export default function HomeLayout({ children }: HomeLayoutProps) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={cn(theme, dmSans.variable)}>
        <AppNavbar />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
